// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nvthongswansea/xtreme/internal/ent/directory"
	"github.com/nvthongswansea/xtreme/internal/ent/file"
	"github.com/nvthongswansea/xtreme/internal/ent/user"
)

// DirectoryCreate is the builder for creating a Directory entity.
type DirectoryCreate struct {
	config
	mutation *DirectoryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (dc *DirectoryCreate) SetName(s string) *DirectoryCreate {
	dc.mutation.SetName(s)
	return dc
}

// SetPath sets the "path" field.
func (dc *DirectoryCreate) SetPath(s string) *DirectoryCreate {
	dc.mutation.SetPath(s)
	return dc
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (dc *DirectoryCreate) SetNillablePath(s *string) *DirectoryCreate {
	if s != nil {
		dc.SetPath(*s)
	}
	return dc
}

// SetIsDeleted sets the "is_deleted" field.
func (dc *DirectoryCreate) SetIsDeleted(b bool) *DirectoryCreate {
	dc.mutation.SetIsDeleted(b)
	return dc
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (dc *DirectoryCreate) SetNillableIsDeleted(b *bool) *DirectoryCreate {
	if b != nil {
		dc.SetIsDeleted(*b)
	}
	return dc
}

// SetCreatedAt sets the "created_at" field.
func (dc *DirectoryCreate) SetCreatedAt(t time.Time) *DirectoryCreate {
	dc.mutation.SetCreatedAt(t)
	return dc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dc *DirectoryCreate) SetNillableCreatedAt(t *time.Time) *DirectoryCreate {
	if t != nil {
		dc.SetCreatedAt(*t)
	}
	return dc
}

// SetUpdatedAt sets the "updated_at" field.
func (dc *DirectoryCreate) SetUpdatedAt(t time.Time) *DirectoryCreate {
	dc.mutation.SetUpdatedAt(t)
	return dc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (dc *DirectoryCreate) SetNillableUpdatedAt(t *time.Time) *DirectoryCreate {
	if t != nil {
		dc.SetUpdatedAt(*t)
	}
	return dc
}

// SetID sets the "id" field.
func (dc *DirectoryCreate) SetID(s string) *DirectoryCreate {
	dc.mutation.SetID(s)
	return dc
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (dc *DirectoryCreate) SetOwnerID(id string) *DirectoryCreate {
	dc.mutation.SetOwnerID(id)
	return dc
}

// SetOwner sets the "owner" edge to the User entity.
func (dc *DirectoryCreate) SetOwner(u *User) *DirectoryCreate {
	return dc.SetOwnerID(u.ID)
}

// AddChildFileIDs adds the "childFiles" edge to the File entity by IDs.
func (dc *DirectoryCreate) AddChildFileIDs(ids ...string) *DirectoryCreate {
	dc.mutation.AddChildFileIDs(ids...)
	return dc
}

// AddChildFiles adds the "childFiles" edges to the File entity.
func (dc *DirectoryCreate) AddChildFiles(f ...*File) *DirectoryCreate {
	ids := make([]string, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return dc.AddChildFileIDs(ids...)
}

// SetParentID sets the "parent" edge to the Directory entity by ID.
func (dc *DirectoryCreate) SetParentID(id string) *DirectoryCreate {
	dc.mutation.SetParentID(id)
	return dc
}

// SetNillableParentID sets the "parent" edge to the Directory entity by ID if the given value is not nil.
func (dc *DirectoryCreate) SetNillableParentID(id *string) *DirectoryCreate {
	if id != nil {
		dc = dc.SetParentID(*id)
	}
	return dc
}

// SetParent sets the "parent" edge to the Directory entity.
func (dc *DirectoryCreate) SetParent(d *Directory) *DirectoryCreate {
	return dc.SetParentID(d.ID)
}

// AddChildDirIDs adds the "childDirs" edge to the Directory entity by IDs.
func (dc *DirectoryCreate) AddChildDirIDs(ids ...string) *DirectoryCreate {
	dc.mutation.AddChildDirIDs(ids...)
	return dc
}

// AddChildDirs adds the "childDirs" edges to the Directory entity.
func (dc *DirectoryCreate) AddChildDirs(d ...*Directory) *DirectoryCreate {
	ids := make([]string, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dc.AddChildDirIDs(ids...)
}

// Mutation returns the DirectoryMutation object of the builder.
func (dc *DirectoryCreate) Mutation() *DirectoryMutation {
	return dc.mutation
}

// Save creates the Directory in the database.
func (dc *DirectoryCreate) Save(ctx context.Context) (*Directory, error) {
	var (
		err  error
		node *Directory
	)
	dc.defaults()
	if len(dc.hooks) == 0 {
		if err = dc.check(); err != nil {
			return nil, err
		}
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DirectoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = dc.check(); err != nil {
				return nil, err
			}
			dc.mutation = mutation
			node, err = dc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			mut = dc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DirectoryCreate) SaveX(ctx context.Context) *Directory {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (dc *DirectoryCreate) defaults() {
	if _, ok := dc.mutation.Path(); !ok {
		v := directory.DefaultPath
		dc.mutation.SetPath(v)
	}
	if _, ok := dc.mutation.IsDeleted(); !ok {
		v := directory.DefaultIsDeleted
		dc.mutation.SetIsDeleted(v)
	}
	if _, ok := dc.mutation.CreatedAt(); !ok {
		v := directory.DefaultCreatedAt()
		dc.mutation.SetCreatedAt(v)
	}
	if _, ok := dc.mutation.UpdatedAt(); !ok {
		v := directory.DefaultUpdatedAt()
		dc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DirectoryCreate) check() error {
	if _, ok := dc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := dc.mutation.Name(); ok {
		if err := directory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if _, ok := dc.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New("ent: missing required field \"path\"")}
	}
	if _, ok := dc.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New("ent: missing required field \"is_deleted\"")}
	}
	if _, ok := dc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New("ent: missing required field \"created_at\"")}
	}
	if _, ok := dc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New("ent: missing required field \"updated_at\"")}
	}
	if v, ok := dc.mutation.ID(); ok {
		if err := directory.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf("ent: validator failed for field \"id\": %w", err)}
		}
	}
	if _, ok := dc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner", err: errors.New("ent: missing required edge \"owner\"")}
	}
	return nil
}

func (dc *DirectoryCreate) sqlSave(ctx context.Context) (*Directory, error) {
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}

func (dc *DirectoryCreate) createSpec() (*Directory, *sqlgraph.CreateSpec) {
	var (
		_node = &Directory{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: directory.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: directory.FieldID,
			},
		}
	)
	if id, ok := dc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := dc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: directory.FieldName,
		})
		_node.Name = value
	}
	if value, ok := dc.mutation.Path(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: directory.FieldPath,
		})
		_node.Path = value
	}
	if value, ok := dc.mutation.IsDeleted(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: directory.FieldIsDeleted,
		})
		_node.IsDeleted = value
	}
	if value, ok := dc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: directory.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := dc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: directory.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if nodes := dc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directory.OwnerTable,
			Columns: []string{directory.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_directories = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dc.mutation.ChildFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directory.ChildFilesTable,
			Columns: []string{directory.ChildFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: file.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dc.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directory.ParentTable,
			Columns: []string{directory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: directory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.directory_child_dirs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dc.mutation.ChildDirsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directory.ChildDirsTable,
			Columns: []string{directory.ChildDirsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: directory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DirectoryCreateBulk is the builder for creating many Directory entities in bulk.
type DirectoryCreateBulk struct {
	config
	builders []*DirectoryCreate
}

// Save creates the Directory entities in the database.
func (dcb *DirectoryCreateBulk) Save(ctx context.Context) ([]*Directory, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Directory, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DirectoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DirectoryCreateBulk) SaveX(ctx context.Context) []*Directory {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
