// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/nvthongswansea/xtreme/internal/ent/directory"
	"github.com/nvthongswansea/xtreme/internal/ent/file"
	"github.com/nvthongswansea/xtreme/internal/ent/schema"
	"github.com/nvthongswansea/xtreme/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	directoryFields := schema.Directory{}.Fields()
	_ = directoryFields
	// directoryDescName is the schema descriptor for name field.
	directoryDescName := directoryFields[1].Descriptor()
	// directory.NameValidator is a validator for the "name" field. It is called by the builders before save.
	directory.NameValidator = directoryDescName.Validators[0].(func(string) error)
	// directoryDescPath is the schema descriptor for path field.
	directoryDescPath := directoryFields[2].Descriptor()
	// directory.DefaultPath holds the default value on creation for the path field.
	directory.DefaultPath = directoryDescPath.Default.(string)
	// directoryDescIsDeleted is the schema descriptor for is_deleted field.
	directoryDescIsDeleted := directoryFields[3].Descriptor()
	// directory.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	directory.DefaultIsDeleted = directoryDescIsDeleted.Default.(bool)
	// directoryDescCreatedAt is the schema descriptor for created_at field.
	directoryDescCreatedAt := directoryFields[4].Descriptor()
	// directory.DefaultCreatedAt holds the default value on creation for the created_at field.
	directory.DefaultCreatedAt = directoryDescCreatedAt.Default.(func() time.Time)
	// directoryDescUpdatedAt is the schema descriptor for updated_at field.
	directoryDescUpdatedAt := directoryFields[5].Descriptor()
	// directory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	directory.DefaultUpdatedAt = directoryDescUpdatedAt.Default.(func() time.Time)
	// directory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	directory.UpdateDefaultUpdatedAt = directoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// directoryDescID is the schema descriptor for id field.
	directoryDescID := directoryFields[0].Descriptor()
	// directory.IDValidator is a validator for the "id" field. It is called by the builders before save.
	directory.IDValidator = directoryDescID.Validators[0].(func(string) error)
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescName is the schema descriptor for name field.
	fileDescName := fileFields[1].Descriptor()
	// file.NameValidator is a validator for the "name" field. It is called by the builders before save.
	file.NameValidator = fileDescName.Validators[0].(func(string) error)
	// fileDescMimeType is the schema descriptor for mime_type field.
	fileDescMimeType := fileFields[2].Descriptor()
	// file.DefaultMimeType holds the default value on creation for the mime_type field.
	file.DefaultMimeType = fileDescMimeType.Default.(string)
	// fileDescPath is the schema descriptor for path field.
	fileDescPath := fileFields[3].Descriptor()
	// file.DefaultPath holds the default value on creation for the path field.
	file.DefaultPath = fileDescPath.Default.(string)
	// fileDescRelPathOnDisk is the schema descriptor for rel_path_on_disk field.
	fileDescRelPathOnDisk := fileFields[4].Descriptor()
	// file.RelPathOnDiskValidator is a validator for the "rel_path_on_disk" field. It is called by the builders before save.
	file.RelPathOnDiskValidator = fileDescRelPathOnDisk.Validators[0].(func(string) error)
	// fileDescSize is the schema descriptor for size field.
	fileDescSize := fileFields[5].Descriptor()
	// file.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	file.SizeValidator = fileDescSize.Validators[0].(func(int64) error)
	// fileDescIsDeleted is the schema descriptor for is_deleted field.
	fileDescIsDeleted := fileFields[6].Descriptor()
	// file.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	file.DefaultIsDeleted = fileDescIsDeleted.Default.(bool)
	// fileDescCreatedAt is the schema descriptor for created_at field.
	fileDescCreatedAt := fileFields[7].Descriptor()
	// file.DefaultCreatedAt holds the default value on creation for the created_at field.
	file.DefaultCreatedAt = fileDescCreatedAt.Default.(func() time.Time)
	// fileDescUpdatedAt is the schema descriptor for updated_at field.
	fileDescUpdatedAt := fileFields[8].Descriptor()
	// file.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	file.DefaultUpdatedAt = fileDescUpdatedAt.Default.(func() time.Time)
	// file.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	file.UpdateDefaultUpdatedAt = fileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// fileDescID is the schema descriptor for id field.
	fileDescID := fileFields[0].Descriptor()
	// file.IDValidator is a validator for the "id" field. It is called by the builders before save.
	file.IDValidator = fileDescID.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
