// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Directory is the predicate function for directory builders.
type Directory func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
